name: Publish

on:
  push:
    tags:
      - v**

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Build
        run: ./gradlew build
      - name: Publish to Modrinth
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
        run: ./gradlew modrinth
      - name: Publish to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          body_path: CHANGELOG.md
          files: build/libs/redstone-relays-*.jar
