name: Publish

on:
  push:
    tags:
      - v**

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.7.0
      - name: Setup Java JDK
        uses: actions/setup-java@v3.10.0
        with:
          java-version: 17
          distribution: temurin
      - name: Build
        run: ./gradlew --no-daemon build
      - name: Publish to Modrinth
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
        run: ./gradlew --no-daemon modrinth
